### ISSUE TITLE
Weird behavior when you set a slice inside ctx.Session

### ISSUE THREAD

**Issue by speedwheel** [iris-contrib/community-board#5]
Please answer these questions before submitting your issue. Thanks!

- [x] I have read the [_examples](https://github.com/kataras/iris/tree/master/_examples), [Contributing File](https://github.com/iris-contrib/community-board/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue was never [posted](https://github.com/iris-contrib/community-board/issues) before.

### What version of Go are you using, minimum 1.8 (`go version`)?

1.8.3

### What operating system and processor architecture are you using (`go env`)?

Ubuntu 16.04

### What version of Iris are you using?

Version 7.0.1

### What did you do?

```go
business := []model.Business{}
business = ctx.Session().Get("businessEdit").([]model.Business)
fmt.Println(business.[0].Name)
//prints "Name"
business[0].Name = "changeName"
fmt.Println(ctx.Session().Get("businessEdit").([]model.Business)[0].Name)
//prints "changeName"
```

For me it's weird that the session modifies without calling ctx.Session().Set()
How can I make var business independent from the session?

### What did you expect to see?
`
ctx.Session().Get("businessEdit").([]model.Business)[0].Name`

should return "Name"

### What did you see instead?
it returned "changeName" instead

**Comment by speedwheel** [comment]
In my opinion, one should first separate the following two concepts:

integers as mathematical objects (that is: values)
variables of type int
Then the answer is: Integer variables are mutable, integer values are immutable.

This view is consistent with the Go specification which states that strings are immutable. Obviously, a string variable is mutable.

Variables (as a concept) in Go are at least:

named variables (such as: var i int)
variables accessible via pointers
Mutable Go objects:

arrays and slices
maps
channels
closures which are capturing at least 1 variable from the outer scope
Immutable Go objects:

interfaces
booleans, numeric values (including values of type int)
strings
pointers
function pointers, and closures which can be reduced to function pointers
structs having a single field
Go objects which some people may consider mutable, while other people may consider them immutable:

structs having multiple fields

**Comment by speedwheel** [comment]
@kataras Answer:

Because it's a slice, the interface{} with a slice is like a pointer. I can fix by checking if it's a slice, and if yes we should return a copy of it.
I think the best solution is to create two methods: SetImmutable(value) and Get(..) will return an immutable object, so the set caller will decide what data is stored.
This will give to the user both performance (raw return) and immutability when the user wants it.

**Comment by kataras** [comment]
Finally @speedwheel , update with `go get -u github.com/kataras/iris`.

Both sessions and context's .Values() have this new function now: 
```go
// SetImmutable fills the session with an entry "value" based on its "key"
// Unlike `Set`, the output value cannot be changed by the caller later on (when .Get)
// An Immutable entry should be only changed with a `SetImmutable`, simple `Set` will not work
// if the entry was immutable, for your own safety.
// Use it consistently, it's far slower than `Set`.
// Read more about muttable and immutable go types: https://stackoverflow.com/a/8021081
SetImmutable(key string, value interface{})
```

Thank you for your report and the time you were waiting for a fix on the [chat](https://kataras.rocket.chat/channel/iris)! 

Please keep note that I still don't recommend saving large data on a session, not only in golang and iris but generally.

**Comment by speedwheel** [comment]
@kataras Thank you for your fast action taking!

I have been testing this morning the new function, using the same code base , but I am seeing the same result like when using .Set().

This is my code basically:

`ctx.Session().SetImmutable("businessEdit", business)`
`business = ctx.Session().Get("businessEdit").([]model.Business)`
`//business[0].Name equals to Edward initially`
`business[0].Name = "Gabriel"`
`fmt.Println(ctx.Session().Get("businessEdit").([]model.Business)[0].Name)`
`Prints out Gabriel`

**Comment by kataras** [comment]
@speedwheel  how this test passes? https://github.com/kataras/iris/blob/master/core/memstore/memstore_test.go#L52

**Comment by kataras** [comment]
@speedwheel The test for the new memstore I did code yesterday to support that kind of things passses, look [here](https://github.com/kataras/iris/blob/master/core/memstore/memstore_test.go#L52) but when I test your code (with sessions) it doesn't, this is very weird, let me investigate it more

**Comment by kataras** [comment]
The new memstore that I did code yesterday to support these kind of things works as expected and the [tests](https://github.com/kataras/iris/blob/master/core/memstore/memstore_test.go#L52) passed. I had to reverese and if statement for the sessions, it's working now I tested for sessions too. Update again and let me know, thank you very much!

**Comment by speedwheel** [comment]
@kataras It's working like a charm now, thank you again for the great support, this was really helpful, and hopefully not only for me.

**Comment by kataras** [comment]
Thank you, I just upgraded all [community's middleware](https://github.com/iris-contrib/middleware) too, you may want to check them, although it doesn't really matter, you can use any third-party middleware
