### ISSUE TITLE
Mark asset routes

### ISSUE THREAD

**Issue by Allendar** [iris-contrib/community-board#8]
### What version of Go are you using, minimum 1.8 (`go version`)?

1.8.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

amd64 darwin

### What version of Iris are you using?

Version 7

###

I was doing some benchmarks and pprof debugging today and noticed that the `app.Favicon`, `app.StaticWeb` etc. are also getting pushed through the MiddleWare I assigned on the main level of the router. This is OK, but I noticed that this actually causes some unneeded overhead in my case.

In my so called `CoreMiddleware` I resolve Domain/Site/User/Userrights/Locale. This always needs to be handled which is perfect, but I also set some base values for all routes like:

```go
c.Values().Set("site", site)
...
c.Values().Set("domain", domain)
...
c.Values().Set("user", user)
```

..as they are practically always used in route logic.

I was thinking it would be nice that the `Context` object would have a `bool` marker inside it (private) and that I could maybe do something like `if !c.IsAsset() { ... }` so the `.Set()` calls don't happen for assets.

I hope this makes sense. I've tested it with a fake marker and it improves my `wrk` benchmark from `~36k` req/sec to `~44k` req/sec.

Thank you!

**Comment by kataras** [comment]
Hello @Allendar , first of all thanks for your detailed proposal, I have to see that kind of issue many months!

To be honesty I'll need a code-snippet or a pseudocode of what are you mean with `c.IsAsset()`. You want to return true if that handler is serving a file to the client? and if yes can you give me a way that makes your route faster? I think the `IsAsset` will take more time than any `Set` call.

**Comment by Allendar** [comment]
Hello @kataras , my question was a bit naive. I debugged some more last night and I noticed it's not the `Set` calls per se. It seems to be the sessions. I will close this issue and make a new one accordingly to it's cause.

**Comment by kataras** [comment]
@Allendar No problem, I'm here whenever you post a new one!
